# 1. Introduction
Some linguistic accounts consider language to be an independent module in the human cognitive domain [e.g., @chomsky1986knowledge; @fodor1983modularity]. In other models language is an independent cognitive capacity associated with other domains [e.g., @hasson2018grounding], but the nature of this dependency is unknown. In the field of language anticipation (henceforth, linguistic anticipation and linguistic prediction), many scholars advocate for a more global view where language is not necessarily independent but its correct functioning depends on the collaboration of a larger non-linguistic cognitive capacities [e.g., @ryskin2020domain]. In a predictive processing view of language, a more general point of view does not sound implausible. There is abundant evidence that all species make predictions [e.g., mammals, @alcaro2011seeking; @wilson2011bird; plants, @appel2014plants]. And humans do not only have the unique ability to generate linguistic predictions (e.g, anticipating the end of words) but additionally make non-linguistic predictions [e.g., while driving, @morando2016drivers; @stahl2016supporting; or while playing sports, @nakamoto2012experts; @wright2010functional].      
In my dissertation, I investigate whether there is an association between a person’s ability to make non-linguistic and linguistic predictions. Finding an association between linguistic and non-linguistic domains and the nature of it if there is one is essential given that anticipation is a basic cognitive action deployed continuously to facilitate information processing in all possible domains. Understanding the association among domains would clarify how different types of cognitive abilities are related, and how different types of cognitive experiences affect encoding and processing of the other theoretically unrelated domains, like for example music and driving.      
To address this question, I examine auditory (pitch, rhythm) and visual-spatial (object in motion) non-language anticipation and language anticipation (a word’s suffix) in adult Spanish monolinguals and English and Mandarin Chinese intermediate and advanced learners of Spanish. Auditory anticipation was selected because numerous studies show that processing in language and other auditory domains such as music are interrelated. For pitch, musicians of a non-tonal L1 are more sensitive to linguistic tone differences than non-musicians of the same L1 [@chua2014effect], and non-musician speakers of tonal L1s perform musical tasks better than non-musician speakers of non-tonal L1s [e.g., @bidelman2013tone; @ngo2016effects]. However, no study has examined whether this extrapolated ability can also be used for prediction or only in perception. For rhythm, rhythm perception and production abilities are positively correlated with foreign prosody perception, and in particular with lexical stress [@cason2019rhythmic]. In contrast to pitch, prediction studies on rhythm have shown that rhythm anticipation is linked to linguistic abilities. For instance, typically developing children anticipate upcoming beats better than dyslexic children [@persici2019rhythmic]. Finally, for visual-spatial processing, some scholars propose that children’s dyslexia is caused by deficits in visual-spatial attention rather than to limited phonological processing [@vidyasagar2010dyslexia]. However, it has not been studied either how these deficits in visual-spatial processing are related to anticipation of linguistic and visual-spatial information.     
In addition to exploring the role of anticipatory experience (association between non-linguistic and linguistic prediction), I investigate the role of language experience (L1 extrapolation; L2 proficiency) and working memory in adult second language acquisition (SLA). In a usage-based framework, language experience is important because it shapes grammar constantly [@bybee2006usage] and so it shifts a speaker’s attention to and inhibition of input. Thus language experience keeps affecting the ability to make predictions in any language.  The inhibition effect is called blocking [@kamin1969predictability] and consists of cues predicting a certain outcome not being encoded as cues because another cue is already encoded as a predictor of that outcome. That is, the speaker has learned to pay attention to that reliable association [learned attention, @mackintosh1975theory]. In the usage-based framework, a speaker in the L2 should be able to resort to that association for successful L2 prediction. However, cue-outcome associations do not always overlap completely, so in the case of partial overlap, it is unknown whether the similar or the discrepancy are stronger in impacting language processing.      
The ability to make cue-outcome associations and use them in prediction may well be conditioned by working memory. Working memory has been shown to contribute to language anticipation sometimes [@huettig2016prediction] but not others [@otten2009does]. The main structures selected to research the influence of working memory on anticipation have been morphosyntactic. The function it plays may, however, be the responsible for the differences in working memory findings. @huettig2016prediction researched anticipation of morphosyntax as an outcome in L1 Dutch and did find working memory differences, while @otten2009does used morphosyntax as the cue and found no effects of working memory. It is however not possible so far to draw many conclusions from the available results on the role of working memory on linguistic anticipation as they are scant. The grounds set by the differences in the use of morphosyntax in language anticipation in @huettig2016prediction and @otten2009does's studies may be a source of findings on the role of working memory on language processing and anticipation if that line of research is further pursued.           
Indeed, morphosyntactic anticipation in general has been very productive in providing insight into how the mechanisms of linguistic prediction. Overall, morphosyntactic information such as gender can be predicted in an L1 [@kamide2003time] and already in an L2 when the L1 has a gender system as well at beginner stages [@dussias2013gender]. Other types of morphosyntactic information such as noun number [@roll2010word] and tense [@sagarra2018suprasegmental] can also be predicted based on phonological cues.     
To investigate the influence of language experience on morphosyntactic prediction based on phonological cues, I compare English and Mandarin Chinese learners of Spanish. Relevant to my dissertation, Mandarin, English and Spanish differ in the presence of tones (present in Mandarin, absent in English and Spanish), lexical stress (present in English and Spanish, absent in Mandarin, although Mandarin tones share the main acoustic correlate with Spanish lexical stress), and morphology (null in Chinese, poor in English, rich in Spanish).     
Studies on learning experience have revealed that adults can anticipate linguistic information in their L1 [e.g., @roll2013word] and might do so in their L2 [e.g., @dussias2013gender], although only extensive active practice result in L2 performance comparable to L1 performance [@lozano2019slowly]. L2 processing and anticipation capabilities are largely constrained by the speaker’s proficiency [e.g., @sagarra2018suprasegmental] and the cross-linguistic effects from the L1 [e.g., @dupoux2008persistent], although how and when the L1 affects L2 processing and anticipation is not clear.      
Studies on the association of auditory abilities have demonstrated that processing and comprehension abilities are not only extrapolated across languages [e.g., @mokari2018perceptual], and also in terms of language and pitch and rhythm abilities [e.g., @tsukada2015perception; @cason2019rhythmic,  respectively]. However, no study has explored the possibility that this extrapolation also reveals itself in anticipation, even though anticipation is present in other auditory domains such as in rhythms _[@]_ or melodic processing _[@]_. Similarly, a relationship has been found between speech processing abilities and visual-spatial abilities [@phillips2004comprehension], but no research on how this relationship extends to anticipation performance has been undertaken.      
The goals of this project are to study cross-linguistic associations over different levels of L2 proficiency, to examine the ability to associate acoustic knowledge to predict non-linguistic information (pitch, rhythm, space), and to explore the role of cognitive individual differences, i.e. working memory, in each of these cases. This project is hence split into three studies: transfer within domain (L1>L2), within modality but between domains (speech>music), between modaliltieses and domains (speech>vision). By completing these studies, this project will inform models of phonological transfer as well as models of working memory, by establishing how different cognitive domains are interrelated.