# 3. Research questions and hypotheses
The relationship between language and other cognitive capabilities in humans is still unclear. In language processing, connectionist accounts argue that processing is dependent on a larger domain-general cognitive structure. And in a predictive processing view of language, anticipation is essential to language processing and comprehension [e.g., @wicha2003potato; @berkum2005anticipating]. Whether and how the ability to generate linguistic predictions relates to other cognitive faculties is unknown. In order to make accurate linguistic predictions, a listener needs to recreate a faithful representation of the linguistic and non-linguistic context in which they are receiving the message. It is reasonable therefore to call linguistic and non-linguistic executive functions into work to take into account all contextual information during language processing [see @ryskin2020domain for a review].     
A domain-general mechanism for linguistic predictive processing is reasonable, as humans can also generate non-linguistic predictions [e.g., while driving, @morando2016drivers; @stahl2016supporting; or while playing sports, @nakamoto2012experts; @wright2010functional]. In addition, other animals [@alcaro2011seeking], birds [@wilson2011bird] and even plants [@appel2014plants] also have the ability to generate (non-linguistic) predictions. There is no research on how the linguistic and non-linguistic anticipatory abilities in humans relate, but there is evidence that different processing domains are related in certain cases.     
Two domains have been related to language: auditory and visuospatial. Pitch knowledge in music, for instance, has been associated with better performance in L2 tone perception when the L1 did not have tone representation [@tang2016musical]. Non-musician L1 tonal speakers perform better in absolute pitch discrimination tasks than their peers from non-tonal L1 languages [@bidelman2013tone]. Rhyhtm performance has also been linked to speech perception and production, in particular as far as L2 lexical stress is concerned [@cason2019rhythmic]. Regarding visuospatial abilities, there is a positive link between the visuospatial domain and reading abilities in languages with orthographic depth. In addition, representation of space affects L1 processing in atypical populations [@landau2005parallels].     
In case anticipatory abilities from different linguistic and non-linguistic domains are associated, it is possible that this association is conditioned by other factors. These factors can be general and apply to all cognition, such as WM, or be more specific and apply only to language, like L1 transfer and L2 proficiency. I conducted a series of studies with L2 speakers of Spanish who speak Mandarin or English as their L1 and compared their performance in several anticipatory and WM tasks with the performance of a monolingual group of Spanish speakers to delve into the possible relationship between linguistic and non-linguistic domains. These studies further explored how other situational factors mediate the cross-domain effects. Participants completed a visual-world paradigm that measured the participants' ability to generate morphosyntactic predictions based on lexical stress, a rhythm anticipation task, a melodic anticipation task based on pitch changes, a visuospatial anticipation task, a verbal WM task, and a visuospatial WM task.
Following the above rationale, the overarching questions for the project are:     

**Study 1**    
	
**RQ1. Do Spanish monolinguals, and intermediate and advanced Mandarin and English learners of Spanish use lexical stress to anticipate verbal suffixes in Spanish? If so, are prediction abilities mediated by verbal WM?**

**H1.** In line with previous similar research, 1) monolingual speakers of Spanish will encounter no difficulty in using stressed and unstressed syllables as cues to verb suffixes,  [@lozano2019slowly; @sagarra2018suprasegmental], and 2) WM will not be responsible for individual variability among L1 Spanish speakers[@otten2009does; @sagarra2018suprasegmental].
Regarding L2 speakers
As for L2 speakers and L1 transfer, L1 Mandarin speakers are expected to extrapolate their knowledge on pitch successfully to make use of lexical stress as a prediction cue [@li2018effect]. L1 English speakers are expected to extrapolate their knowledge on lexical stress contrastive function to make use of lexical stress in Spanish as an anticipatory cue [@lozano2019slowly; @sagarra2018suprasegmental]. Regarding L2 proficiency, both groups are expected to be able to use lexical stress as a cue only at advanced levels of proficiency. Finally, an increased verbal WM is expected to affect extrapolation efficiency positively [@huettig2016prediction] and to bring the start of the effects of cross-linguistic association forward in the L2 acquisition process.
	 
**Study 2**     
	 
**RQ2. Is linguistic prediction of word morphology associated with auditory prediction in Spanish monolinguals, and intermediate and advanced Chinese and English learners of Spanish? If so, how do WM, L1 transfer and L2 proficiency mediate this relationship?**

**H2.** _Pitch_
In monolingual speakers, no effects of better pitch anticipation are expected to have an effect on individual variability of morphosyntactic anticipation based on lexical stress, as all participants are non-musicians and come from a similar linguistic background. WM is only expected to have an effect on non-linguistic auditory prediction abilities [@roden2014does].     
In L2 speakers, Mandarin L1 speakers are expected to anticipate melodic information faster than any of the other populations since they will be extrapolating their pitch knowledge from language to music. However, the performance in anticipating melodic information will not be correlated with their L2 anticipation performance. That is, the influence will be unidirectional from language to music. No association between pitch and speech prediction abilities in the English learners groups. L2 proficiency and pitch anticipatory abilities are not expected to be correlated, as facilitative processing of L2 speech by pitch has only been confirmed with musicians [@slevc2006individual]. All auditory anticipation scores will be positively correlated with verbal WM scores in the L2 speakers [@yang2017bilinguals].     

_Rhythm_
Contrary to pitch, better rhythm anticipation abilities are expected to be associatd with individual variability of speech anticipation in monolingual speakers of Spanish. This result would stem from on-beat timings facilitating L1 speech processing [@cason2012rhythmic], so individuals with better rhythm synchronization abilities would be resorting to their rhythmic abilities to anticipate speech based on prosody more efficiently. Like with pitch, WM is only expected to have an effect on non-linguistic auditory prediction abilities [@colley2018working].     
Contrarily, rhythmic anticipation abilities are expected to be positively correlated with L2 anticipation performance, as rhythmic abilities are a reliable predictor of lexical stress placement [@cason2019rhythmic], and therefore of lexical stress comprehension. This influence will be visible at all levels of proficiency and regardless of the L1. That is, better rhythmic abilities will translate into better anticipation performance based on lexical stress when compared to peers around the same proficiency range in both L1s. Like before, L2 proficiency and rhythm anticipatory abilities are not expected to be correlated, because while better rhythm promotes correct L2 perception and production [@cason2019rhythmic], anticipation adds another layer of processing difficulty that has been proven to be too complex in the L2 [e.g., @hopp2015semantics; @mitsugi2016use]. All auditory anticipation scores will be positively correlated with verbal WM scores in the L2 speakers [@roden2014does].     
    
**Study 3**     

**RQ3. Is linguistic prediction of word morphology associated with visuospatial prediction in Spanish monolinguals, and intermediate and advanced Chinese and English learners of Spanish? If so, how do WM, L1 transfer and L2 proficiency mediate this relationship?**

**H3.** Language prediction abilities in the L1 are not expected to be associated with the visuospatial domain. I am comparing two different modalities: auditory (speech) and visuospatial. While there is a relationship between space representation word processing in reading [@katz1992reading; @schmalz2015getting], I hypothesize that speech and space representation are cognitively too far apart to influence each other. Verbal WM will not be associated with speech anticipation performance, but it might be associated with visuospatial WM due to cross-domain influence [@colley2018influence]. Visuospatial WM performance will in return be associated with visuospatial anticipation, as visual performance is generally more clearly associated with WM [e.g., @pan2014working; @woodman2004visual]. 
No association between anticipation in the visuospatial domain and the speech domain is expected to be found in L2 speakers either, for the same reasons. Therefore, it does not matter what the L1 or the L2 is, or the proficiency in the L2, increased abilities to anticipate movements in space through vision will not be associated with speech in any way. Verbal WM will not be associated with speech anticipation performance [@sagarra2018suprasegmental]. Visuospatial WM performance will be associated with visuospatial anticipation, and with verbal WM [@ma2016working], at least in intermediate L2 speakers [@yang2017bilinguals].