# 6. Conclusion
The goal of this dissertation was to examine the role of language experience (L1 transfer, L2 proficiency) (Study 1), non-linguistic auditory prediction (Study 2), and visuospatial prediction (Study 3), on L1 and L2 linguistic prediction of word endings based on prosodic cues. In addition, this dissertation explored the mediation of verbal and visuospatial WM morphosyntactic anticipation based on lexical stress in the L1 and the L2. Spanish monolinguals and intermediate and advanced Mandarin and English learners of Spanish completed a linguistic anticipation task, a pitch anticipation task, a rhythm anticipation task, a visuospatial anticipation task, a verbal WM task, and a visuospatial anticipation task. The linguistic anticipation task, a visual-world paradigm, tested the participants’ ability to predict verb tense suffixes in L2 Spanish based on the stressed or unstressed first syllable of the verb. In this task, the L1 English speakers were hypothesized to transfer lexical stress function [@sagarra2018suprasegmental], and L1 Mandarin speakers were hypothesized to transfer acoustic correlate knowledge [@li2017effects]. Both transfers were expected to be as costly, and their effects only visible at higher levels of proficiency. Therefore, only L2 speakers at higher proficiencies and monolinguals would be able to generate the correct predictions, but the L2 speakers would not reach a target-like performance [@perdomo2019prosodic]. Verbal WM was expected to foster both types of transfer [@huettig2016prediction].    
Across non-linguistic domains, auditory predictive abilities were hypothesized to be correlated positively with linguistic predictive abilities, given that there is already some evidence of rhythm and prosody perception [@cason2019rhythmic], and pitch in music and suprasegmental perception [@chua2014effect], but visuospatial predictive abilities were hypothesized to not be associated with linguistic predictive abilities. L2 proficiency and L1 transfer were not expected to mediate associations between language and other non-linguistic anticipation abilities. WM was expected to account for individual differences in anticipation, but only in the non-linguistic anticipation tasks.         
Results confirming these hypotheses would confirm that different cognitive domains in the auditory modality can influence speech anticipation, and thus that anticipation relies at least partially on domain-general cognitive mechanisms. These results would also confirm, however, that the underlying anticipatory mechanisms are only common within modality, but not shared across modalities, and therefore better anticipatory abilities in other modalities do not affect linguistic prediction.