# 5. The studies
## 5.1. Study 1 – Linguistic anticipation
Study 1 investigated the role of language experience (L1 transfer, L2 proficiency) and WM on adults’ ability to use stress cues to predict verb suffixes during spoken word recognition. Previous research shows that adult L2 learners transfer L1 prosodic information when perceiving the L2are able to transfer and extrapolate prosody encoding abilities from their L1 to their L2 [@krishnan2010effects]. Furthermore, L2 learners use L2 acoustic information to make predictions between words [@perdomo2019prosodic] and within words [e.g., @roll2015neurolinguistic; @sagarra2018suprasegmental].      
Particularly relevant to the present study, @sagarra2018suprasegmental investigated use of lexical stress to predict verb suffixes in native and non-native speakers. Spanish monolinguals and beginning and advanced English learners of Spanish completed a visual-world paradigm with sentences containing Spanish verbs in the present and the preterit tenses. As a reminder, lexical stress is contrastive in English and Spanish, but the acoustic correlates are different in each language. They found that advanced English learners of Spanish could use Spanish lexical stress to predict verb tense information. Intermediate speakers could still not use that connection. The ability to generate this prediction was not mediated by WM. 
The English speakers in @sagarra2018suprasegmental's study might have selected to transfer function knowledge from all the information encoded along with lexical stress in English. It is not possible to confirm that hypothesis because there was no population with which to compare that might have transferred other information, like Mandarin L1 speakers could do with acoustic knowledge. L2 proficiency conditioned the English speakers' ability to anticipate morphosyntax in Spanish.  In the case that Mandarin speakers also anticipate, it is possible their proficiency also conditions their ability to generate the correct predictions, and therefore, only advanced speakers are able to predict verb tense when cued through lexical stress.      
Lastly, WM is the cognitive skill to store temporarily and process incoming information so complex cognitive actions are executed [@baddeley2007working]. Variability in WM have been found to be one of the possible factors mediating L2 anticipation [@huettig2016prediction found effects;  @sagarra2018suprasegmental; @otten2009does found none]. The specific role of WM on L2 anticipation or how it interacts with other factors is not clear. In order to clarify these issue, WM has so been included.      
The research question for Study 1 was whether Spanish monolinguals, and intermediate and advanced Mandarin and English learners of Spanish use lexical stress to anticipate verbal suffixes in Spanish. In the case that they do so, whether their prediction abilities are mediated by verbal WM. The hypotheses are found in Section 3. The findings of Study 1 will inform the models SLM, PAM-L2 and L2LP of L2 phonology acquisition by expanding their theoretical tenets to suprasegmental information, as well as cognitive models of SLA.

## 5.2. Study 2 – Auditory anticipation: pitch, rhythm, and morphosyntactic anticipation
Study 2 examined whether speech anticipation is language-specific or it relies on more general auditory mechanisms also shared by other cognitive skills related to audition, in native and non-native speakers. This study also explores whether WM has any impact on the sharing of the mechanisms. @lozano2019slowly found that practice can lead to transfer of auditory processing abilities across linguistic domains. WM capacities have been shown to be associated across the auditory and visuospatial domains [@kane2004generality], such that lasting improvement in the auditory area, for example, has effects in the visual domain [@bergman2014music]. In particular, this study focuses on shared mechanisms of language with two auditory phenomena: rhythm and pitch. 
Rhythm is a pattern of recurrent time intervals that usually occur periodically [@berlyne1971aesthetics]. A listener needs to anticipate when the next beat or event signaling the end of an interval and beginning of the next one is coming in order to move or act synchronously. Rhythm abilities have been linked positively to L2 prosody processing [@cason2019rhythmic]. Pitch is the frequency associated to a sound wave so it sounds high or low during perception [@klapuri2006introduction]. For pitch, previous findings point towards a positive relationship between musical abilities and prosodic abilities regarding absolute pitch (Ngo et al., 2016), and out-of key tunes violate melodic prediction in musicians and non-musicians in Western music at least (e.g., Sherwin & Sajda, 2013). There is therefore the possibility that rhythmic, pitch, and linguistic anticipation based on prosody are correlated.
The research question for Study 2 was whether linguistic prediction of word morphology is  associated with auditory prediction in Spanish monolinguals, and intermediate and advanced Chinese and English learners of Spanish. If so, how WM, L1 transfer and L2 proficiency mediate this relationship. The hypotheses are found in Section 3. Spanish monolinguals and intermediate and advanced Mandarin and English learners of Spanish completed a linguistic prediction task and two non-linguistic auditory tasks: a pitch task and a rhythm task. The findings of Study 2 will provide insight into how independent the language anticipatory function is in human cognition, or how it relies on common processing mechanisms that also underlie information prediction in other domains, namely, pitch and rhythm.

## 5.3. Study 3 – Linguistic and non-linguistic visuospatial anticipation
Study 3 explored whether visuospatial capacities affect linguistic anticipation in native and non-native speakers, and how WM influences that relationship. The link between linguistic and visuospatial cognitive systems is not a new matter for research. Several frameworks have been proposed [e.g. @barrouillet2004time; @baddeley1986working; @baddeley1996exploring; @baddeley2012working; @baddeley1974working; @cowan1999embedded] trying to capture how these systems may be interrelated modalities. Indeed, visual and auditory-verbal binding WM in children is positively associated with their word recognition skills [@wang2015evaluating]. More specifically, visual attention span is a significant predictor of reading fluency at both beginning and advanced stages of literacy and can also predict orthographic knowledge and spelling performance in Dutch children [@van2015specific]. Space representation and processing also affect linguistic performance in atypical populations [e.g., @bochynska2020spatial; @landau2005parallels]. However, there is no research focusing on how space information processing affects other types of information processing.
The research question for Study 3 was whether linguistic prediction of word morphology is associated with visuospatial prediction in Spanish monolinguals, and intermediate and advanced Chinese and English learners of Spanish. In that were the case, how WM, L1 transfer and L2 proficiency mediate this relationship. The hypotheses are found in Section 3. Spanish monolinguals and intermediate and advanced Mandarin and English learners of Spanish completed a linguistic prediction task, a one non-linguistic visuospatial task, a verbal WM task, and a visuospatial WM task. The findings of Study 3 will clarify how anticipation in different cognition modalities are connected, and whether different processing and anticipatory mechanisms are domain specific or underpinned by common cognitive resources to different domains, namely, auditory and visuospatial.  