# 1. Introduction
Humans tend to anticipate information: when watching a movie, when driving, when playing sports, when listening to music. We also anticipate information in hearing speech, when reading, or when producing a linguistic message, especially when we are immersed in our first language (L1). While prediction is so pervasive in our lives, the nature of prediction mechanisms is unknown. Here I investigate how speakers transfer their L1 predictive mechanisms onto a L2. In particular, how acoustic and function knowledge is transferred to use suprasegmentals as cues to morphosyntactic outcomes. Understanding how morphosyntactic prediction works is crucial because it modulates anticipation at other linguistic levels [@guajardo2014morphosyntax].        
To address this goal, I examine verbe tense anticipation based off lexical stress in adult Spanish monolinguals and English and Mandarin Chinese intermediate and advanced learners of Spanish. The conditioning factors I consider are language experience-related: L1 transfer and L2 proficiency, and cognitive (i.e., working memory, WM). In a usage-based framework, language experience is important because it shapes grammar constantly [@bybee2006usage] and so it shifts a speaker’s attention to and inhibition of input.             
L1 transfer in particular can affect the type of information that a speaker pays attention to by default because that information is important in the L1 and thus is encoded and activated in a regular basis. This inhibition effect is called blocking [@kamin1969predictability] and prevents the speaker from encoding L2 cues associated to an outcome, because a previous cue transferred from the L1 is already encoded as a predictor of that outcome. Sometimes the L1 encoded cue can successfully lead to the correct outcome, but these cue-outcome mappings rarely fully overlap cross-linguistically. In cases of partial overlap, it is unclear whether the similarity or the discrepancy is stronger in impacting language processing.
L2 proficiency affects the variety of linguistic contexts, words and structures that a learner has been exposed to, and the frequency with which the learner has encountered them. In theory, the larger the exposure, the easier to create a cue-outcome mapping. Language experience thus continuously influences a speaker's ability to make predictions in any language they speak. Cognitive factors like WM may also be responsible for the inability to make L2 predictions. There are few studies, however, delving into how WM capacities affect speakers' abilities especially in L2s to generate the predictions.                    