# 2. Background
## 2.1. Language anticipation
In a predictive processing view of language, language processing is facilitated and preceded by prediction of linguistic information based on cues already available at different linguistic and non-linguistic levels [e.g., @federmeier2007thinking; @wicha2003potato]. These cues are associated with an outcome and the mapping helps generate the correct prediction [@delong2005probabilistic; @dikker2011before]. Speakers used a wide range of phonological, morphosyntactic, semantic and contextual cues to anticipate linguistic outcomes in their L1. Morphosyntactic anticipation in particular is very important because it modulates anticipation at other linguistic layers, like semantic choices [@guajardo2014morphosyntax].      
L2 processing is oftentimes difficult, and L2 anticipation is not a typical event. Studying the influence of L1 prediction mechanisms on L2 anticipation might explain why learning and understanding an L2 is so troublesome, and why attaining native-like proficiency in an L2 is rare. This influence might be mediated by cognitive capacities. Understanding and processing a L2 is more cognitively taxing than speaking a L1 because the L2 overtakes the pool of executive functions usually applied in L1 anticipation [@linck2014working], especially at non-proficient levels. So when the cognitive executive resources are excessively loaded, they are undermined and this overtaxing may also hindered L2 predictive processing. 

### 2.1.1. L1 processing and anticipation
Language anticipation is a productive and dynamic cognitive mechanism in our L1. Speakers use a wide range of morphosyntactic [@gruter2016l2], syntactic [@linzen2016uncertainty], semantic [@kamide2003time; @pozzan2016semantic] and phonological cues to generate predictions on semantic [@altmann1999incremental], morphosyntactic [@gruter2016l2; @lew2010real] and syntactic-discoursive outcomes [@gruter2013l2]. Among the phonological cues we use, we encounter coarticulation [@salverda2014immediate], intonation [@nakamura2012immediate; @weber2006role], lexical stress [@correia2013word; @sagarra2018suprasegmental], pauses between clauses [@hawthorne2014pauses; @kjelgaard1999prosodic], vowel duration [@rehrig2017acoustic], and tone [@roll2015neurolinguistic; @roll2011activating]. Phonological cues are oftentimes associated with word suffixes [@roll2010word; @sagarra2018suprasegmental; @soto2001segmental].       
Phonological cues exert an influence on the predictions that are generated in both proximal and distal sentential contexts. Lexical stress in English is signaled through proximal cues like syllable's F0, duration, and amplitude, but also through distal cues like meter patterns [@brown2015metrical], such that distal cues interact with the proximal ones during lexical segmentation and word recognition [@brown2011expectations]. As a consequence, violating lexical stress expectations created by distal cues in terms of location and syllabic structure elicit anormal brain activity associated with a more costly processing [@domahs2008processing].
Phonological phenomena are closely tied to morphosyntactic suffixes, with relationships that vary across languages. In Central Swedish, a low tone cues the singular suffix in a noun (*fisken* 'fish~[SG]~'), and a high tone cues the plural suffix [*fiskar* 'fish~[PL]~,' @roll2010word; @soderstrom2015using; @roll2013word]. Likewise, low tone cues present tense ( _skrämmer_ 'I scare'), and a high tone cues past tense [*skrämde* 'I scared,' @soderstrom2012processing; @roll2015neurolinguistic]. Similarly, lexically stressed syllables in Spanish cue present tense (*CANta* 'he sings'), while lexically unstressed syllables cue past tense [*canTÓ* 'he sang,' @sagarra2018suprasegmental]. The presence or absenece of lexical stress at the beginning of a noun in Spanish can also signal what noun should be activated when several segmental competitors are possible [*PRINcipe* 'prince' vs. *prinCIPIO* 'beginning,' @soto2001segmental]. Lastly, shorter vowel duration in verbs in English is associated with active voice ('the girl was pushing the boy'), whereas longer vowel duration is associated with passive voice ['the girl was pushed by the boy;' @rehrig2017acoustic].         
Individual variability in cognitive capacities (i.e., WM) does not exert a great impact on linguistic anticipation in typical adult individuals, at least in simple morphological structures or in speech [@ye2008involvement]. The few online studies so far on the connection between WM and language anticipation generally suggest that WM variability is not a factor in determining the efficacy and characteristics of morphosyntactic prediction generation in Dutch [@otten2009does], Spanish [@sagarra2018suprasegmental] or English [@pakulak2010proficiency; @tanner2014erps]. Although @huettig2016prediction did find in a different study that WM could account for variability in Dutch gender morphosyntax anticipation. Since this last study shares with the previous one either language studied, or structure researched, or methodology employed, none of these can explain the different results on the influence of WM on language anticipation.      
In sum, L1 speakers generate predictions at different linguistic levels. If, when and how WM could affect the capacity to generate L1 predictions has still not been established, although findings suggests WM plays a minor role. Behavioral performance and brain activity may largely be conditioned by different levels of linguistic complexity or linguistic experience, so that WM only affects linguistic anticipation in certain cases.              

### 2.1.2. L2 processing and anticipation
*L1 transfer and L2 proficiency*       
Anticipation in a L2 is not as straightforward as in a L1. Results are especially mixed in the morphosyntactic domain. Morphosyntactic anticipation has been researched with gender [@dussias2013gender; @hopp2016learning; @lew2010real], verbal tense [@sagarra2018suprasegmental; @schremm2016implicit], number [@marull2017second], case [@hopp2015semantics; @mitsugi2016use], and cross-linguistic form similarity. The mixed results have been accounted for by factors like L1 transfer, or L2 proficiency.         
Regarding gender, L2 German speakers may not be able to generate gender predictions [@hopp2016learning], while L2 Spanish speakers may be able to do so [@dussias2013gender], although only under specific linguistic circumstances [@lew2010real]. Contrary to gender, number is more difficult to anticipate, so only advanced speakers can make number predictions [Spanish, @marull2017second], and L2 case is not predicted [German, @hopp2015semantics; Japanese, @mitsugi2016use]. For verbal tense, only L2 learners at advanced levels of proficiency can generate predictions in Spanish [@sagarra2018suprasegmental], but intermediate learners can already make predictions in Central Swedish [@schremm2016implicit].    
Studies varied in whether morphosyntax was used as the cue, the outcome, or both. The L1s were also different, so L1 transfer could have interacted with the role of morphosyntax in determining whether the L2 speakers were able to generate gender morphosyntactic predictions. L2 proficiency and maybe even WM can also partially account for the ability to make L2 predictions. All these conditioning factors have often been entangled in research, so it is difficult to tease their inluence apart. In gender anticipation, having a similar morphosyntactic system in the L1 can help generate predictions in the L2, even at lower levels of proficiency. This is the case of L1 Italian speakers anticipating gender suffixes in L2 Spanish at beginner stages [@dussias2013gender]. Extrapolating L1 knowledge is also the case of L1 English speakers using definiteness in articles to predict nouns at intermediate proficiency stages [@lew2010real]. And L1 transfer can also be seen in L1 English speakers generating predictions in L2 Dutch more efficiently when they use cue determiners that share similar forms with their L1 determiners [@liburd2014investigating]. In contrast, lacking such L1 system may hinder the generation of L2 predictions. This would be the case of L1 English speakers generating gender suffix predictions in L2 Spanish [@dussias2013gender].      
The stability and nature of the encoded L2 morphosyntactic system may influence whether predictions are generated or not. In German, L2 speakers are able to generate comprehension gender predictions only when they are also able to use the L2 gender system target-like in production [@hopp2013grammatical; @hopp2016learning]. In L2 Spanish, speakers may only predict gender suffixes when the nouns are highly frequent [@lew2010real].     
Overcoming this anticipation hurdle might be facilitated when at least a phonological layer is involved and the L2 linguistic experience is larger. English is a poor language in terms of verbal morphology when compared to Spanish. However, when morphosyntax is cued phonologically through lexical stress, advanced L2 Spanish speakers overcome the obstacle and generate verb suffix predictions [@sagarra2018suprasegmental]. L2 speakers of Swedish are also able to generate tense suffix predictions based on tones beginning at intermediate stages of proficiency [@schremm2016implicit].     
However, there are a few considerations to bear in mind when studying transfer effects in phonological cues, since having a similar structure in the L1 does not guarantee it can be used for anticipation in the L2. Whereas advanced L2 Spanish speakers whose L1 is English learn to use lexical stress as a cue [@sagarra2018suprasegmental], L1 French speakers rarely if ever learn to encode lexical stress as an anticipatory cue in L2 Spanish, simply because they do not learn to discriminate it [@dupoux2008persistent] even if French has lexical stress. In contrast, L1 Cantonese and L1 Mandarin speakers learn to discriminate lexical stress in L2 English [@chen2013chinese; @li2017effects], and L1 Koreans also learn to a certain extent [@hualde2015acquisition; @lee2019perception], even though none of these three languages encodes lexical stress. Although it has not been investigated whether these three populations learn to use lexical stress as a cue, these results suggest that the suprasegmental structure in the L1 can not only affect positively or not affect processing of L2 suprasegmental structures, but also affect L2 processing negatively depending on the L1 suprasegmental characteristics. This hypothesis would align with previous results that suggest that L1 non-tonal speakers can learn to use L2 tones as suprasegmental cues to morphosyntax [@hed2019neural; @schremm2016implicit].
In the case that L2 speakers create the mappings between prosodic cue and morphosyntactic outcome thanks to L1 sound encoding transfer, the mapping may not always reach native-like efficiency [@perdomo2019prosodic]. This loss of efficiency has not been accounted for in any model of L2 phonological acquisition. There are some models nevertheless on L2 segmental acquisition that could be adapted to explain how L1 transfer affects L2 prosody-based linguistic anticipation. Here I focus on the Second Language Linguistic Perception model [L2LP, @escudero2005linguistic; @escudero2009linguistic; @leussen2015learning] because it was thought out to explain and predict L2 sound perception phenomena. In L2LP, L2 sounds are perceived through the L1 filter, that is, how they would be perceived if they were pronounced in the speaker's L1. Therefore, the acoustic similarities and discrepancies between the two phonological systems will shape the development of the encoding in the bilingual's mind. In L2 sound acquisition, a copy of the L1 system is created during the initial stages, this copy starts to adjust with exposure via the Gradual Learning Algorithm, a comparison of the L1 system and the perceived L2 sounds. The algorithm offers three possibilities: a new sound is assimilated to multiple L1 sounds, a new sound is perceived as similar to another one in the L1 system, or a new sound does not equal any category in the L1 so it requires a new category for itself. Recent revisions to the model have further proposed that perceiving is not the same thing as recognizing, but there is still not enough research in this direction to formulate any hypothesis.
This model might be able to explain L2 suprasegmental acquisition and its use for predictive processing because it proposes that the 'components' of the L1 sound will affect how the L2 sound is perceived, so having practice perceiving a correlate in the L1 should in theory ease L2 perception of that same correlate. This hypothesis would be supported by L1 tonal speakers learning L2 tones more easily than L1 non-tonal speakers [@chan2019lexical]. The fact that L2 speakers can learn to perceive or discriminate L2 suprasegmentals like lexical stress or tones even when the suprasegmental is absent in their L1, does not necessarilty mean that the L2 speakers can further use the learned sound to generate anticipation. The recent revisions to the L2LP specifically offer a trampoline into accounting for this step from discrimination processing to anticipatory processing.     
A problem that this or other models of L2 phonological acquisition have is that they might not be able to answer how the function of the suprasegmental in the L1 affects acquisition of the L2 suprasegmental structure, and how the function could influence perception even if acoustically the L1 and L2 structures are different. Speakers of two languages that have a function in common might transfer the function also when the acoustic correlates that characterize the function in each language differ. If function transfer were the case, the models would need to be adapted to cover this transfer too, and to explain how function transfer and acoustic correlate transfer differ.       
*Working memory*           
Linguistic knowledge and experience affect language processing and anticipation, especially in L2s. Evidence for that is French L1 speakers struggling to process L2 lexical stress in Spanish [@dupoux2008persistent], arguably because their French lexical stress encoding blocks acquisition of L2 lexical stress with different properties. However, even in these non- or barely sensitive individuals, there are individual differences. Those individuals displaying greater sensitivity to stress differences also retain stress information longer in their WM [@schwab2020working]. We should therefore consider cognitive differences beside linguistic factors when studying L2 acquisition, processing and anticipation.
WM is the cognitive skill that allows to store incoming information temporarily and process it so other complex cognitive actions can be executed [@baddeley2007working]. Three main models of WM stand out: @just1992capacity’s domain-specific single-resource model, @baddeley2007working’s domain-specific multiple-resource model, and domain-free connectionist models. In the domain-specific single-resource model [@just1992capacity], WM capacity constrains language learning and processing. There is also a trade-off between the ability to process and to store linguistic information. This trade-off comes as a consequence of the competition amongst the different actions required for a shared pool of cognitive resources that need to be divided. Therefore, when a task depletes or overtax the WM capacity of a person, their storage capacity diminishes and their processing slows down. In domain-specific multiple-resource model [@baddeley2007working’] WM capacity also constrains linguistic performance, but the cognitive resources are organized differently. A central executive controls three subsystems: the short-term storage phonological loop, the short-term storage visuospatial sketchpad, and the episodic buffer. These three slave systems have independent limited capacities. The two short-term memory systems focus on content, while the episodic buffer connects its sister systems with the long-term memory. The central executive coordinates the activity of the whole entity by filtering the information received, assembling information from different sources into meaningful episodes, regulating the flow of information among the subsystems, shifting tasks, and shifting retrieval strategies. Lastly, connectionist models are domain-free as language capacities are determined by domain-general cognitive abilities. Specifically, by the ability to select which information to pay attention to and which information to inhibit, regardless of the nature of that information. In connectionist models there is no difference between processing and storage. Instead, WM is the activation of part of the long-term memory according to short-term patterns of activations related to domain-specific stores [e.g., @cowan2016working].     

WM influences L2 processing but the specific nature of this influence has still not been completely figured out. Some studies have found facilitating effects of WM on morphosyntactic processing [e.g., @sagarra2016eye; @sanz2016one], while others have found no effect [e.g., @foote2011integrated; @grey2015role]. These differences might be explained by the interaction with factors explained above, like variability in L2 proficiency and the cognitive load imposed by the task and the WM test [@sagarra2017longitudinal]. Speakers at a lower proficiency might then be more susceptible to WM overload [@serafini2016evidence]. In L2 anticipation, higher WM learners may anticipate more easily agreement elements than lower WM individuals [@reichle2016working]. Although the communication context may condition this ability: WM may mediate morphosyntactic prediction only under cognitively taxing conditions [@lozano2020], although this finding is not definitive, as a previous study revealed no effecs of WM on L1 and L2 Spanish speakers’ capacity to anticipate verbal tense based on lexical stress [@sagarra2018suprasegmental].                
The literature in L2 anticipation show that speakers can achieve some success in L2 anticipation depending on their L1, the cues they need to process, their level of proficiency, and maybe their WM capacities, but their performance will rarely be native-like [@perdomo2019prosodic]. A possible explanation for the varied results on L2 perception and anticipation might be found in what speakers are transferring from their L1 (acoustic knowledge vs. function knowledge) that interacts with the new L2 structures they need to encode. Whereas L2 speakers’ anticipation performance might depend on their ability to perceive the cues and what needs to be anticipated, asymmetries amongst studies and the lack of cognitive measures also difficult comparison of results. The lack of a common theoretical framework, the use of non-standardized measures to assess proficiency [self-assessment, @lew2010real], the variety of tasks [e.g. eye-tracking, @sagarra2018suprasegmental; vs offline, @dupoux2008persistent], a variety of L1s [@hed2019neural], and the unclear distinction of variables [e.g., @schremm2016implicit] call for further research where the possible factors accounting for L2 anticipation patterns are better distinguished.      

## 2.2. Linguistic phenomena
### 2.2.1. Lexical stress
Stress is the prominence of a syllable that speakers hear relative to the other syllables in the prosodic word [@hualde2005sounds]. The characteristics of lexical stress, such as acoustic correlates or position within words, vary widely across languages. In English and Spanish, lexical stress has no fixed position, but it position changes from word to word playing a phonologically contrastive function at the lexical level. This function is much more typical in Spanish than it is in English. In English, lexical stress is used predominantly to distinguish heteronyms or pairs of verb-noun that have no segmental differences (to “proDUCE,” verb vs. “PROduce,” noun). In Spanish, lexical stress differentiates all kinds of word categories and information, such as verbal tense and person (*CANto* “I sing” vs. *canTÓ* “s/he sang”), or nouns (*PApa* “potato” vs. *paPÁ* “dad”), or nouns from verbs (*TÉRmino* “term” vs. *terMIno* “I finish” vs *termiNÓ* “s/he finished”).         
Different acoustic correlates, their importance or weight, and how they combine cause the acoustic realization of lexical stress in each specific language to vary. In Spanish, the most reliable cues to stress are pitch (F0), duration and intensity [@hualde2005sounds; @ortega2006phonetic; @ortega2007disentangling; @ortega2009perception]. Pitch is higher for stressed syllables and lower for unstressed syllables, and stressed syllables sound louder and are usually slightly longer. The main cues in English are vowel duration and quality [@cooper2002constraints; @cutler1986forbear]. Thus, unstressed vowels are centralized.                  
Thanks to the lexically contrastive function, lexical stress helps in activation of lexical entries in L1 Spanish [@soto2001segmental], such that a prosodically matching cue to the target ( _prinCI_ > _prinCIpio_, “start”) results in shorter and more accurate activation times, when compared to mismatching cues ( _PRINci_ > _prinCIpio_ 'start'). These results suggest that participants were using the suprasegmental cues in lexical stress to anticipate the lexical element. L1 English speakers, in contrast, may only be able to use lexical stress as a cue when more than one syllable of the word has already been heard [@cooper2002constraints]. @perdomo2019prosodic provide evidence of activation through prediction in even earlier syllables in the L1 English speakers, however, more in line with the performance of the L1 Spanish speakers in @soto2001segmental's study. This difference in performance among studies probably results from the cues that speakers use to discriminate lexical stress, and how these cues are weighted in the language. That is, English L1 speakers may be placing a larger reliance on duration to process Spanish lexical stress. This reliance would be transferred from L1 English processing. Spanish L1 speakers may be relying more on other cues, such as pitch and intensity, that are discarded by the English speakers because they are not as informative in English [@ortega2013english].     
The differences and similarities in cue weighting can influence lexical stress perception in an L2. For example, @cooper2002constraints found that the similar distribution of stress in Dutch and English helped L1 Dutch learners of English transfer their knowledge of lexical stress to process it properly in L2 English. But, in contrast, German speakers have more difficulty perceiving stress in another free lexically stressed language such as Spanish than L1 speakers [@schwab2016use]; again, maybe due to the acoustic correlates they use to discriminate the suprasegmental. And L1 English L2 Spanish speakers can only use lexical stress as a cue in Spanish at advanced levels of proficiency [@sagarra2018suprasegmental]. A possible explanation is that the setting of lexical stress in English did not match the Spanish lexical stress encoding and thus prevented them from using it properly until they reached a certain level of linguistic experience. Following this line of reasoning, @vickie2010cross suggested that language background in the L1 can affect how lexical stress is perceived in an L2 and what correlates are used to discriminate the L2 stress.     
The studies above suggest that the acoustic properties of prosody are essential in processing and activating incoming linguistic information. The importance speakers assign to each cue might extend beyond perception and affect anticipation as well. Studies like @vickie2010cross' further suggest that speakers resort to their prosodic abilities in the L1 in order to process other prosodic structures in their L2 absent in their L1, such that Chinese speakers can use pitch knowledge to discriminate lexical stress in Spanish, even if they lack that suprasegmental in their L1. Extending this hypothesis, L2 speakers might be able to transfer acoustic knowledge and function and reassemble them into new prosodic structures that are encoded in the L2 lexicon and use it as cues for language anticipation. Specifically, L1 speakers of lexically free stressed languages may transfer the function knowledge, and L1 tonal speakers might be able to transfer pitch knowledge to encode L2 lexical stress that is based primarily on pitch. After lexical stress has been encoded in the L2 lexicon thanks to L1 pitch knowledge, L2 speakers might learn to use this new prosodic structure as the basis for L2 prediction so as to reduce the processing cognitive load.

### 2.2.2. Tone
Tones are the pitch contour patterns of the voiced part in syllables [@chao1968grammar]. Many languages use tones, or changes in pitch-contour, at a phrasal level for pragmatic purposes. However, only a few use tones contrastively at a lexical level. The acoustic correlates for tones vary across languages: some use only pitch (e.g., most Mandarin Chinese dialects), whereas others also use length and/or register (e.g., Cantonese Chinese). Relevant to this with Mandarin Chinese speakers, in most Mandarin Chinese dialects (e.g., from Beijing and Tianjin), the main and oftentimes only acoustic correlate for tones is changes in pitch (F0) contour or changes in pitch height within a syllable [@gandour1978perception; @zhu2015tone]. Mandarin tones facilitate word recognition (@malins2010roles), although segmental cues are the primary activator, especially vowels [@hu2012dissociation; @sereno2015contribution; @wiener2016constraints]. The role of tone is thus integration of the activated lexical item in the higher context.  
Knowledge of the nature and function of tones in the L1 can affect L2 tone learning both positively and negatively by providing a background knowledge to which learners resort to acquire the L2 tones and compare them. @li2017effects examined the influence of the L1 tonal knowledge in the acquisition of L2 tones in children. These children were L1 Cantonese speakers learning L2 Mandarin, and they had issues in categorizing Mandarin tones 1 and 4, as these tones would be assimilated to the same tone 1 category in Cantonese. In the case of these children, being a native speaker to a tonal language helped them in the perception of Mandarin tones 2 and 3, but it hindered perception of other L2 tones because the knowledge transfer from L1 tones disagreed from the L2 tone structure and interfered with it.    
The role of tones in Mandarin is different from the role of lexical stress in Spanish. Mandarin speakers need to pay attention to the pitch variations in order to assign the correct tone to the word they are hearing. Since pitch variations are the basis for lexical stress in Spanish, Mandarin speakers might be able to transfer their sensitivity to pitch changes to process and use pitch to anticipate linguistic information more easily than English speakers. In comparison, pitch variation is not as important an acoustic correlate in English lexical stress, so L1 English speakers may not be sensitive to L2 pitch information in lexical stress, at least in beginning and intermediate stages of proficiency. Therefore, L1 English speakers need to learn to distinguish pitch variations since they can only transfer function knowledge, while Mandarin speakers may transfer pitch knowledge but need to learn function in using lexical stress to anticipate verbal tense in L2 Spanish.