# 6. Discussion
We investigated the effect of L1 transfer, L2 proficiency and L2 use on Mandarin and English L2 learners of Spanish's ability to use associations of lexical stress with verbal tense morphology for L2 prediction.
Participants completed a visual-world paradigm in Spanish and we compared them to a monolingual Spanish controls.
Results revealed that all speakers were anticipating the verb suffix at the offset of the initial syllable in the verbs.
Increased L2 proficiency and use facilitated prediction, although advanced speakers never reached  monolingual-like anticipation.
There were no significant different between the two L2 groups.
The fact that monolingual speakers anticipated tense suffix at target syllable offset agrees with previous studies [e.g., @lozano2020slowly; @sagarra2018suprasegmental].
These results serve as evidence that the previous findings are generalizable and that we can compare the findings about the L2 populations to other previous studies too.
We discuss the findings on the L2 speakers following the research questions.

*1. **L1 transfer**: Does transfer affect L2 learners’ ability to make stress-suffix tense associations during spoken word processing?* 
We predicted that English speakers would anticipate tense suffix at the offset of the preceding syllable, and that they would do so faster than Mandarin speakers. 
We expected Mandarin speakers to be at chance level.
Our results support our prediction that English speakers would anticipate, as evidenced by the increased fixations on the target at target syllable offset.
The results, however, do not support our prediction regarding Mandarin speakers, as they were also anticipating above chance at target syllable offset.

The finding that English speakers were anticipating matches previous studies showing that advanced English speakers can use morphophonological associations for prediction in L2 Spanish during spoken language processing when the phonological cue is contained in a syllable with consonant-vowel-consonant structure [e.g., @lozano2020slowly; @sagarra2018suprasegmental].
The previous study on processing of morphophonological associations focusing on the role of L2 proficiency tested beginners and advanced L2 speakers [@sagarra2018suprasegmental], the present study adds to that literature by showing that intermediate English speakers can also generate morphophonological predictions, at least when living immersed in the L2.
In addition, this study also provides evidence for the first time that native speakers of Mandarin Chinese dialect also generate morphophonological predictions in L2 Spanish at intermediate and advanced levels of proficiency.
Together with the studies on Swedish morphophonological associations [e.g., @gosselke2018neural; @schremm2016implicit], these studies suggest that L2 speakers can learn to use this type of associations to facilitate language processing regardless of their L1.

We did not find a main effect of L1 transfer in the GCA, but the difference did show up in the GLMMs. 
The GLMMs showed that Mandarin speakers anticipated less than English speakers.
These results suggest that L1 transfer is modulated by other factors, and thus its effects should be studied and interpreted in combination with the effects of those other factors.
One such factor is L2 proficiency.


*2. **L2 proficiency**: Does L2 proficiency affect L2 learners’ ability to make stress-suffix tense associations during spoken word processing?* 
We had predicted that higher proficiency would be correlated with more and faster prediction.
Accordingly, our results suggest that more proficient speakers predicted more than less proficient speakers.
We had also predicted that even highly proficient speakers would not anticipate to the same extent as monolingual speakers.
This prediction was also confirmed.

The results on proficiency can be explained through language exposure.
An increased proficiency indicates that the L2 speaker has had more contact with the L2 and their L2 linguistic knowledge is broader.
This broader experience may be allowing the speakers to improve their efficiency in using morphophonological predictions during l2 processing.

The gap between advanced L2 speakers and the monolingual speakers is in line with previous experiments in morphophonological associations [e.g., @perdomo2019prosodic; @sagarra2018suprasegmental], which has led some authors to conclude that L2 speakers will rarely attain monolingual-like processing efficiency [@perdomo2019prosodic].
The present study, however, does not lend itself to support or counterevidence such conclusion.
While the present study included some near native advanced speakers as indicated by the proficiency measure, they are likely to few to draw conclusions as to whether monolingual-like efficiency is possible.
Future studies may want to recruit more participants at that level of proficiency to test whether attainment of monolingual-like efficiency is possible or not.

In the case of the advanced speakers in these studies, their lagging comparison to the monolingual speakers may be explained through two venues.
In the first one, L2 speakers may have less stable and direct associations between lexical stress and its contrastive function.
Inability to completely use lexical stress to contrast words may result, in turn, in a weaker association with tense suffixes.
Thus, even if advanced L2 speakers perceive the differences in stress, the weak association with the suffixes prevent them from using morphophonological associations as confidently as monolingual speakers do.
The lagging can be explained with a second reason, and that is L1 transfer.
Monolingual speakers of Spanish have representations of lexical stress, its functions and associations in their first linguistic system.
That is, when they learned lexical stress, there was no other information that could conflict with it.
L2 speakers, in contrast, already have a linguistic system in place that interacts with the new one.
If we learn an L2 sound system taking as reference our L1 sound system, as some models suggest _(e.g., )_, it is possible that some noise from this sound system remains, making the L2 lexical stress representation less "clean" and therefore less reliable.
Future studies may examine whether explicit instruction, or at least focused training [@hed2019neural; @schremm2017influence], may help in getting rid of the noise or preventing its inclusion in the first place.

In the English speakers, the effects of L2 proficiency differed depending on what tense had to be anticipated.
Present tense was anticipated earlier than preterit tense.
This advantage is probably due to the higher frequency of present tense in speech.
In this tense, proficiency did not exert a big influence, as its effects were probably counteracted by the frequency of occurrence of the tense in daily life.
Preterit tense, in contrast, was more susceptible to proficiency effects.
In this tense, the higher the proficiency of the L2 learner, the earlier the anticipation was.
L1 transfer that could explain why this interaction appeared in the English speakers but not in the Mandarin Chinese speakers.
Since preterit tense is not as frequent, speakers need to resort to other strategies for processing.
One such strategy is the knowledge they have in their L1 about lexical stress.
English speakers know about the contrastive function of lexical stress and can thus transfer that knowledge to distinguish between tenses.
Mandarin speakers do not have a contrastive function associated with stress, and thus do not count with that resource to help during word processing.
In their case, knowledge of lexical stress in the L1, if they have it [@selkirk1990prosodic], may be confused with tone representation, making it impossible for them to transfer lexical stress knowledge successfully.
The contrast between Mandarin and English speakers indicates that L1 transfer is a positive influence for the L1 English speakers, while there are no effects in the case of L1 Chinese speakers.

The facilitatory effects of L1 transfer at higher levels of proficiency are in line with a study on production of L2 Chinese tones [@shih2010prosody], in which even advanced learners show effects of L1 transfer.
In @schih2010prosody's study, native Chinese speakers and English learners of Mandarin were tested in their production of lexical tones.
Tone production at earlier stages of proficiency was characterized by English-like alternations.
At intermediate stages, the influence of English in Chinese prosody was less obvious, but target-like production of tones was still unstable.
At advanced stages, lexical tone production improved considerably but learners still showed difficulties when the tones appeared in medial positions of phrases.
The authors argue that this problem may stem from the speakers trying to transfer the stressed/unstressed distinction from English.
This problem did not arise in earlier stages because less proficient speakers do not have enough command to express that contrast.
Following this reasoning, advanced English speakers were more benefited than intermediate ones from L1 transfer because they were fluent enough to have automatized the contrast between present and preterit tense.
The similarity between lexical stress in English and Spanish would have resulted in the facilitatory effects, in contrast with @schih2010prosody's study, where the structure in the L1 (lexical stress) and the L2 (lexical tone) conflicted.


*3. **Language use**: Does language use affect L2 learners’ ability to make stress-suffix tense association during spoken word processing?* 
We predicted that a greater use of Spanish would be associated with more and more accurate prediction.
This prediction is borne out by our results.
Specifically, a higher percentage of use of Spanish per week was associated with a higher probability of predicting.
Although both L2 groups benefited of a larger amount of Spanish use, the effects were different depending on the group.
In the English speakers, speaking Spanish more often resulted in increased prediction in the preterit tense, but it made no difference in the present tense.
In the Mandarin speakers, speaking Spanish more often resulted in barely any variability in prediction ability in the preterit tense, but created much variability in the present tense.

<!-- How to explain these results?-->

The present study is the first study exploring how L2 use affects processing of morphophonological associations.
Just as increased L2 use helps in morphophonological association, L2 use is likely to be a reliable predictor of successful processing in other areas such as morphosyntax.
As relates to morpophonological associations, future studies could expand the findings here by focusing on training.
Previous studies on training of Swedish morphophonological associations in Swedish suggest that targeted training can help in acquisition of these associations [@schremm2017influence].
Training does not only direct L2 learners attention towards the association, but increases its use.
Training is therefore likely to help L2 learners acquire morphophonological associations in Spanish as well as in Swedish.
In addition, training different L1s can also expand findings on the role of L1 transfer and its interaction with L2 use.
